### ISSUE TITLE
Setup file

### ISSUE THREAD

**Issue by prarthanaa994** [Shakesbeery/vigiPy#1]
It would be really great if the setup file is shared. We are doing a project on pharmacovigilance .We are programming in python.It would be really great if the setup file for vigipy package is available

**Comment by Shakesbeery** [comment]
Hey! Thanks for your interest in pharmacovigilance in python. I'll work on setting up the setup.py file so it can be consumed as a module. I'll let you know here when it's done.

**Comment by prarthanaa994** [comment]
Thanks  a lot...

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Shakesbeery** [comment]
I have added a `setup.py` file and instructions in the readme. You should be able to install and start experimenting. Let me know if it works and I can close this issue. Thanks!

**Comment by prarthanaa994** [comment]
Thank you for the proactive response.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
